name: "canopen2HAmqtt"
description: "canopen2HAmqtt gateway"
slug: "canopen2hamqtt"
init: false

version: "latest"
homeassistant: "2025.5.3"
usb: true
uart: true
udev: true
kernel_modules: true
host_network: true
privileged:
  - NET_ADMIN

image: "ghcr.io/rgoskolkov/canopen2hamqtt"

arch:
  - aarch64

map:
  - addon_config

options:
  interface: socketcan
  channel: 'can0'
  bitrate: 125000
  mqtt_server: mqtt://can2mqttuser:can2mqttuser@core-mosquitto
  mqtt_topic_prefix: homeassistant
  watchdog_timeout: 60
  configure_can_interface: true
  devices:
    - vendor_id: 0x00000BEE
      product_code: 0x0000F103
      eds_file: "bluepill.eds"
      model_name: "blue-pill-relay-can"

schema:
  interface: str
  channel: str?
  bitrate: int
  mqtt_server: str
  mqtt_topic_prefix: str?
  sdo_response_timeout: float?
  watchdog_timeout: int?
  configure_can_interface: bool?
  extra_args: str?
  devices:
    - vendor_id: int
      product_code: int
      eds_file: str
      model_name: str
