[project]
name = "canopen2HAmqtt"
version = "0.3.0"
authors = [
    {name="Mariusz Kryński", email="mrk@sed.pl"},
    {name="Roman Oskolkov", email="oksollkof@gmail.com"}
]
requires-python = ">=3.8"

dependencies = [
    "python-can",
    "aiomqtt<2",
    "pyserial",
    "coloredlogs",
]

[project.scripts]
canopen2HAmqtt = "main:main"

[project.optional-dependencies]
dev = [
    "black"
]

[tool.setuptools]
py-modules = ["main"]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
