[project]
name = "canopen2HAmqtt"
version = "0.3.0"
authors = [
    {name="Mariusz Kryński", email="mrk@sed.pl"},
    {name="Roman Oskolkov", email="oksollkof@gmail.com"}
]
requires-python = ">=3.8"

dependencies = [
    "canopen@git+https://github.com/mrk-its/canopen-asyncio#egg=feature-asyncio",
    "aiomqtt<2",
    "pyserial",
    "coloredlogs",
    "pyinotify==0.9.6",
    "awesomeversion==24.6.0",
    "pyasyncore",
]

[project.scripts]  # Optional
canopen2HAmqtt = "main:main"

[project.optional-dependencies]
dev = [
    "black"
]

[tool.setuptools.package-data]
canopen2HAmqtt = ["eds/*.eds"]
